# Default values for VSS-based Blue-Green Deployment

app:
  name: my-app
  image: gcr.io/heptio-images/ks-guestbook-demo

blue:
  version: blue
  imageTag: "1.0.0-blue"
  trafficWeight: 100  # Initially, 100% traffic goes to Blue (can be gradually decreased)
  route: test  # Test route to verify Blue deployment

green:
  version: green
  imageTag: "1.0.0-green"
  trafficWeight: 0  # Initially, 0% traffic goes to Green (will be gradually increased)

service:
  name: my-app-service
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - my-app.example.com
